title: S端derelbe Archiv
url: "http://localhost:4000"
description: S端derelbe Archiv
keywords: Geschichte, Archiv, B端cherhalle, Stadtteil, Hamburg, S端derelbe
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

gems:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings
markdown: kramdown
kramdown:
  parse_block_html: true
  auto_ids: false
